/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf Model.jsx
Author: Jiří Kuba (https://sketchfab.com/kuba.jirka)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shopping-cart-model-5ce63640d40340be940138c9b90d5eec
Title: Shopping cart model
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

// @ts-ignore
export default function ShoppingCartModel(props) {
  // @ts-ignore
  const { nodes, materials } = useGLTF("/shopping_cart_model/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[-0.007, -0.378, 1.026]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes.CageSite_0.geometry}
            material={materials.Metal}
          />
          <mesh
            geometry={nodes.CageSite_0_1.geometry}
            material={materials.Metal}
          />
          <mesh
            geometry={nodes.CageSite_0_2.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[4.35, 6.947, -5.41]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={0.557}
        >
          <mesh
            geometry={nodes.Cylinder004_0.geometry}
            material={materials.WheelTire}
          />
          <mesh
            geometry={nodes.Cylinder004_1.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[-2.76, -6.28, -5.41]}
          rotation={[Math.PI / 2, 1.047, 0]}
          scale={0.557}
        >
          <mesh
            geometry={nodes.Cylinder008_0.geometry}
            material={materials.WheelTire}
          />
          <mesh
            geometry={nodes.Cylinder008_1.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[2.87, -6.28, -5.41]}
          rotation={[Math.PI / 2, 1.047, 0]}
          scale={0.557}
        >
          <mesh
            geometry={nodes.Cylinder007_0.geometry}
            material={materials.WheelTire}
          />
          <mesh
            geometry={nodes.Cylinder007_1.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[-4.355, 6.947, -5.41]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={0.557}
        >
          <mesh
            geometry={nodes.Cylinder003_0.geometry}
            material={materials.WheelTire}
          />
          <mesh
            geometry={nodes.Cylinder003_1.geometry}
            material={materials.Metal}
          />
        </group>
        <mesh
          geometry={nodes.Torus009_0.geometry}
          material={materials["Metal.001"]}
          position={[4.35, 6.947, -5.41]}
          rotation={[1.423, 0, 0]}
          scale={[0.047, 0.448, 0.448]}
        />
        <mesh
          geometry={nodes.Torus012_0.geometry}
          material={materials.Metal}
          position={[0.003, 5.81, 4.33]}
          rotation={[1.423, 0, 0]}
          scale={[0.403, 0.375, 0.375]}
        />
        <mesh
          geometry={nodes.CageFront_0.geometry}
          material={materials.Metal}
          position={[-0.086, -5.194, 0.779]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Torus004_0.geometry}
          material={materials.Metal}
          position={[0.093, 0, 0]}
        />
        <mesh
          geometry={nodes.Torus005_0.geometry}
          material={materials.Metal}
          position={[0.003, 6.135, 4.33]}
          rotation={[1.423, 0, 0]}
          scale={[0.482, 0.448, 0.448]}
        />
        <mesh
          geometry={nodes.Torus002_0.geometry}
          material={materials.Metal}
          position={[0.003, 7.099, 4.423]}
          rotation={[1.423, 0, 0]}
          scale={[0.519, 0.448, 0.448]}
        />
        <mesh
          geometry={nodes.Torus008_0.geometry}
          material={materials.Metal}
          position={[0.006, -6.274, -0.202]}
          scale={[0.687, 0.719, 0.719]}
        />
        <mesh
          geometry={nodes.Torus003_0.geometry}
          material={materials.Metal}
          position={[0.003, 6.937, -4.17]}
          rotation={[1.423, 0, 0]}
          scale={[0.5, 0.448, 0.448]}
        />
        <mesh
          geometry={nodes.Torus006_0.geometry}
          material={materials.Metal}
          position={[0.027, 2.971, -3.923]}
          scale={[0.482, 0.448, 0.448]}
        />
        <mesh
          geometry={nodes.CageFront001_0.geometry}
          material={materials.Metal}
          position={[8.423, -0.536, -1.283]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Cylinder005_0.geometry}
          material={materials.Metal}
          position={[4.35, 6.947, -4.228]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={0.377}
        />
        <mesh
          geometry={nodes.Cylinder009_0.geometry}
          material={materials.Metal}
          position={[-2.76, -6.28, -4.228]}
          rotation={[-Math.PI, 0, -Math.PI / 3]}
          scale={0.377}
        />
        <mesh
          geometry={nodes.Torus010_0.geometry}
          material={materials.Metal}
          position={[-2.76, -6.28, -5.41]}
          rotation={[1.401, -0.517, -0.085]}
          scale={[0.047, 0.448, 0.448]}
        />
        <mesh
          geometry={nodes.Torus011_0.geometry}
          material={materials.Metal}
          position={[2.87, -6.28, -5.41]}
          rotation={[1.401, -0.517, -0.085]}
          scale={[0.047, 0.448, 0.448]}
        />
        <mesh
          geometry={nodes.Cylinder006_0.geometry}
          material={materials.Metal}
          position={[2.87, -6.28, -4.228]}
          rotation={[-Math.PI, 0, -Math.PI / 3]}
          scale={0.377}
        />
        <mesh
          geometry={nodes.CageFront002_0.geometry}
          material={materials.Metal}
          position={[-0.305, 4.48, 1.077]}
          rotation={[2.995, 1.57, 0]}
          scale={[0.621, 0.991, 0.959]}
        />
        <mesh
          geometry={nodes.Torus013_0.geometry}
          material={materials.Metal}
          position={[0.003, -6.29, 5.957]}
          rotation={[0.113, 0, 0]}
          scale={[0.468, 0.448, 0.448]}
        />
        <mesh
          geometry={nodes.Cylinder001_0.geometry}
          material={materials.Metal}
          position={[-4.355, 6.947, -4.228]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={0.377}
        />
        <mesh
          geometry={nodes.Torus007_0.geometry}
          material={materials["Metal.001"]}
          position={[-4.355, 6.947, -5.41]}
          rotation={[1.423, 0, 0]}
          scale={[0.047, 0.448, 0.448]}
        />
        <mesh
          geometry={nodes.Cylinder010_0.geometry}
          material={materials.RedPlastic}
          position={[-4.697, 8.261, 8.866]}
          rotation={[0.301, Math.PI / 2, 0]}
          scale={0.465}
        />
        <mesh
          geometry={nodes.Cylinder012_0.geometry}
          material={materials.RedPlastic}
          position={[4.68, 8.261, 8.866]}
          rotation={[0.301, Math.PI / 2, 0]}
          scale={0.465}
        />
        <mesh
          geometry={nodes.Torus021_0.geometry}
          material={materials.Metal}
          position={[-4.685, 7.654, 7.931]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.404}
        />
        <mesh
          geometry={nodes.Cylinder011_0.geometry}
          material={materials.RedPlastic}
          position={[-0.11, 8.261, 8.883]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.3, 0.3, 9.198]}
        />
        <mesh
          geometry={nodes.Torus014_0.geometry}
          material={materials.Metal}
          position={[4.683, 7.654, 7.931]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.404}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/shopping_cart_model/scene.gltf");
