/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf
Author: pamoan10 (https://sketchfab.com/pamoan10)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/shopping-cart-opened-d01658d342d943329c1db78de4fa71fa
Title: Shopping cart (opened)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ShoppingCartModel(props) {
  const { nodes, materials } = useGLTF("/shopping_cart_opened/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 2.292]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes["tocut001_Material_#25_0"].geometry}
            material={materials.Material_25}
            position={[0, 0, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
            scale={[0.3, 0.3, 0.3]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/shopping_cart_opened/scene.gltf");
